### ISSUE TITLE
版本支持

### ISSUE THREAD

**Issue by chuchushijingxi** [Linyuzai/concept#22]
大佬，是不是不支持 JDK 17 + springboot 3.0 版本呀，将版本替换后发现无法注入 WebSocketLoadBalanceConcept bean 了,还是我哪里设置的不对。

```java 
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'cstreamingAnswerNotifyStrategy': Unsatisfied dependency expressed through field 'concept': Error creating bean with name 'webSocketLoadBalanceConcept' defined in com.github.linyuzai.connection.loadbalance.websocket.WebSocketLoadBalanceConfiguration: Failed to instantiate [com.github.linyuzai.connection.loadbalance.websocket.concept.WebSocketLoadBalanceConcept]: Factory method 'webSocketLoadBalanceConcept' threw exception with message: Error creating bean with name 'connectionSubscriber' defined in class path resource [com/github/linyuzai/connection/loadbalance/websocket/servlet/ServletWebSocketConceptConfiguration.class]: Post-processing of merged bean definition failed
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:716)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:696)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:145)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:483)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1416)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:597)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:973)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:942)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:608)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:436)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
	at com.cstreaming.cheersu.signaling.CheersuSignalingApplication.main(CheersuSignalingApplication.java:23)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'webSocketLoadBalanceConcept' defined in com.github.linyuzai.connection.loadbalance.websocket.WebSocketLoadBalanceConfiguration: Failed to instantiate [com.github.linyuzai.connection.loadbalance.websocket.concept.WebSocketLoadBalanceConcept]: Factory method 'webSocketLoadBalanceConcept' threw exception with message: Error creating bean with name 'connectionSubscriber' defined in class path resource [com/github/linyuzai/connection/loadbalance/websocket/servlet/ServletWebSocketConceptConfiguration.class]: Post-processing of merged bean definition failed
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:659)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:647)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1332)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1162)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1417)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1337)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:713)
	... 20 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.github.linyuzai.connection.loadbalance.websocket.concept.WebSocketLoadBalanceConcept]: Factory method 'webSocketLoadBalanceConcept' threw exception with message: Error creating bean with name 'connectionSubscriber' defined in class path resource [com/github/linyuzai/connection/loadbalance/websocket/servlet/ServletWebSocketConceptConfiguration.class]: Post-processing of merged bean definition failed
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:171)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:655)
	... 33 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'connectionSubscriber' defined in class path resource [com/github/linyuzai/connection/loadbalance/websocket/servlet/ServletWebSocketConceptConfiguration.class]: Post-processing of merged bean definition failed
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:575)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$1(AbstractBeanFactory.java:365)
	at com.github.linyuzai.connection.loadbalance.autoconfigure.scope.TagScope.lambda$get$0(TagScope.java:17)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at com.github.linyuzai.connection.loadbalance.autoconfigure.scope.TagScope.get(TagScope.java:17)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:362)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:225)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveNamedBean(DefaultListableBeanFactory.java:1310)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveNamedBean(DefaultListableBeanFactory.java:1271)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveBean(DefaultListableBeanFactory.java:484)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:339)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:332)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1173)
	at com.github.linyuzai.connection.loadbalance.autoconfigure.scope.ScopeHelper.getBean(ScopeHelper.java:41)
	at com.github.linyuzai.connection.loadbalance.websocket.WebSocketScopeHelper.getBean(WebSocketScopeHelper.java:20)
	at com.github.linyuzai.connection.loadbalance.websocket.WebSocketLoadBalanceConfiguration.webSocketLoadBalanceConcept(WebSocketLoadBalanceConfiguration.java:112)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:139)
	... 34 common frames omitted
Caused by: java.lang.IllegalStateException: Failed to introspect Class [com.github.linyuzai.connection.loadbalance.websocket.javax.ContainerWebSocketConnectionSubscriber] from ClassLoader [jdk.internal.loader.ClassLoaders$AppClassLoader@63947c6b]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:483)
	at org.springframework.util.ReflectionUtils.doWithLocalMethods(ReflectionUtils.java:320)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.buildLifecycleMetadata(InitDestroyAnnotationBeanPostProcessor.java:297)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.findLifecycleMetadata(InitDestroyAnnotationBeanPostProcessor.java:274)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.findLifecycleMetadata(InitDestroyAnnotationBeanPostProcessor.java:203)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessMergedBeanDefinition(InitDestroyAnnotationBeanPostProcessor.java:182)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessMergedBeanDefinition(CommonAnnotationBeanPostProcessor.java:296)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyMergedBeanDefinitionPostProcessors(AbstractAutowireCapableBeanFactory.java:1083)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:572)
	... 55 common frames omitted
Caused by: java.lang.NoClassDefFoundError: javax/servlet/ServletContext
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402)
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2504)
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:465)
	... 63 common frames omitted
Caused by: java.lang.ClassNotFoundException: javax.servlet.ServletContext
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 67 common frames omitted

Disconnected from the target VM, address: '127.0.0.1:62513', transport: 'socket'

Process finished with exit code 1
```

**Comment by Linyuzai** [comment]
看异常是没有`javax.servlet.ServletContext`，可以看下是不是有`jakarta.websocket:jakarta.websocket-api`这个依赖，如果有的话看是不是还有这个类（没有的话可能高版本改了？）
我是在`com.github.linyuzai.connection.loadbalance.websocket.javax.ContainerWebSocketConnectionSubscriber`这个类里面用了`org.springframework.web.context.ServletContextAware`这个类

JDK 17 + springboot 3.0 我确实还没有测试过，之后会测一下

**Comment by chuchushijingxi** [comment]
![image](https://github.com/Linyuzai/concept/assets/36877983/132f83f1-cb4d-4740-9eac-20c543735f42)
好像是没有这个类了。。现在有啥能临时解决的方法嘛

**Comment by Linyuzai** [comment]
> ![image](https://user-images.githubusercontent.com/36877983/273421366-132f83f1-cb4d-4740-9eac-20c543735f42.png)
> 好像是没有这个类了。。现在有啥能临时解决的方法嘛

好像搞错了，是在`tomcat-embed-core`里面有，你可以自己实现一下`ServletContextAware`看看有没有问题

**Comment by chuchushijingxi** [comment]
> jakarta



> > ![image](https://user-images.githubusercontent.com/36877983/273421366-132f83f1-cb4d-4740-9eac-20c543735f42.png)
> > 好像是没有这个类了。。现在有啥能临时解决的方法嘛
> 
> 好像搞错了，是在`tomcat-embed-core`里面有，你可以自己实现一下`ServletContextAware`看看有没有问题

springboot 3.0 jdk 17  都变成 jakarta 包下面了。。之前的都是javax😭😭😭

**Comment by Linyuzai** [comment]
找到问题了，高版本把`javax.servlet`改成了`jakarta.servlet`，所以找不到了

你可以自己注入`ConnectionSubscriber`，可以参考`JavaxWebSocketConceptConfiguration#connectionSubscriber`或者`ServletWebSocketConceptConfiguration#connectionSubscriber`，把里面的包名换掉

**Comment by chuchushijingxi** [comment]
> 找到问题了，高版本把`javax.servlet`改成了`jakarta.servlet`，所以找不到了
> 
> 你可以自己注入`ConnectionSubscriber`，可以参考`JavaxWebSocketConceptConfiguration#connectionSubscriber`或者`ServletWebSocketConceptConfiguration#connectionSubscriber`，把里面的包名换掉

😨😨  搞不定了。。好多的错误

**Comment by Linyuzai** [comment]
> > 找到问题了，高版本把`javax.servlet`改成了`jakarta.servlet`，所以找不到了
> > 你可以自己注入`ConnectionSubscriber`，可以参考`JavaxWebSocketConceptConfiguration#connectionSubscriber`或者`ServletWebSocketConceptConfiguration#connectionSubscriber`，把里面的包名换掉
> 
> 😨😨 搞不定了。。好多的错误

额，你就直接复制一份，然后改下包名就行了

**Comment by chuchushijingxi** [comment]
> JavaxWebSocketConceptConfiguration

![image](https://github.com/Linyuzai/concept/assets/36877983/c8abd739-bbeb-47df-aae6-1bb45f1ab003)
改成这样还是一样的错误 🤕🤕  是我操作错了嘛

**Comment by chuchushijingxi** [comment]
> > > 找到问题了，高版本把`javax.servlet`改成了`jakarta.servlet`，所以找不到了
> > > 你可以自己注入`ConnectionSubscriber`，可以参考`JavaxWebSocketConceptConfiguration#connectionSubscriber`或者`ServletWebSocketConceptConfiguration#connectionSubscriber`，把里面的包名换掉
> > 
> > 
> > 😨😨 搞不定了。。好多的错误
> 
> 额，你就直接复制一份，然后改下包名就行了
![image](https://github.com/Linyuzai/concept/assets/36877983/0a00a710-9428-49ca-83df-3e3aef75e76e)
改成这样还是一样的错误   😵‍💫😵‍💫
![image](https://github.com/Linyuzai/concept/assets/36877983/94e31d2a-3090-461b-b1bb-2649e873c0b0)
是这里的 javax.websocket.server.ServerContainer 还需要修改嘛

**Comment by Linyuzai** [comment]
就ConnectionSubscriber自定义之后注入一下就行了，其他的不需要复制出来，`javax.websocket.server.ServerContainer`b不太清楚哎，可能也需要吧

**Comment by chuchushijingxi** [comment]
> 就ConnectionSubscriber自定义之后注入一下就行了，其他的不需要复制出来，`javax.websocket.server.ServerContainer`b不太清楚哎，可能也需要吧

大佬可以写个例子看看嘛 😥😥  弄不明白了。。

**Comment by Linyuzai** [comment]
> > 就ConnectionSubscriber自定义之后注入一下就行了，其他的不需要复制出来，`javax.websocket.server.ServerContainer`b不太清楚哎，可能也需要吧
> 
> 大佬可以写个例子看看嘛 😥😥 弄不明白了。。

你可以试一下2.2.0版本，用servlet（javax不支持），应该是没有这个问题了，不过里面的配置会有区别
https://github.com/Linyuzai/concept/wiki/Concept-WebSocket-LoadBalance-2
