### ISSUE TITLE
concept-downlaod可以下载到服务器指定路径

### ISSUE THREAD

**Issue by guixin29** [Linyuzai/concept#43]
concept-download 可以下载到服务器指定路径么，需求就是将服务器里的图片按照一定的逻辑重新存到另一个地方。。。

**Comment by Linyuzai** [comment]
可以用异步的方式拿输入流写到指定的路径 https://github.com/Linyuzai/concept/wiki/Concept-Download-2#异步消费

或者用DownloadMock https://github.com/Linyuzai/concept/wiki/Concept-Download-2#mock支持beta210

**Comment by guixin29** [comment]
![图片](https://github.com/Linyuzai/concept/assets/28587546/1071d835-64db-4006-97a4-8d0836e949f9)  下载后为压缩包

**Comment by Linyuzai** [comment]
如果就是换个目录的话，直接手动处理或用commons和hutool的工具类就行了吧

**Comment by guixin29** [comment]
主要是要将文件分类，想到下载的方法哪里可以直接设置，用这个就方便些。。。

**Comment by guixin29** [comment]
![图片](https://github.com/Linyuzai/concept/assets/28587546/def8305e-d80d-41c0-ab71-38c567143993)
设置异步，设置文件路径名称会报错。。。

**Comment by Linyuzai** [comment]
发一下完整的堆栈

**Comment by guixin29** [comment]
2024-05-27 16:19:49 INFO [http-nio-80-exec-1] org.apache.tomcat.util.http.parser.Cookie: A cookie header was received [Hm_lvt_d9c8b87d10717013641458b300c552e4=1705199021,1705283967,1705298393,1705299393;] that contained an invalid cookie. That cookie will be ignored.
 Note: further occurrences of this error will be logged at DEBUG level.
2024-05-27 16:19:49 INFO [http-nio-80-exec-1] o.a.c.core.ContainerBase.[Tomcat].[localhost].[/]: Initializing Spring DispatcherServlet 'dispatcherServlet'
2024-05-27 16:19:49 INFO [http-nio-80-exec-1] org.springframework.web.servlet.DispatcherServlet: Initializing Servlet 'dispatcherServlet'
2024-05-27 16:19:49 INFO [http-nio-80-exec-1] org.springframework.web.servlet.DispatcherServlet: Completed initialization in 2 ms
2024-05-27 16:19:49 INFO [http-nio-80-exec-1] c.g.linyuzai.download.core.logger.DownloadLogger: Download >> [OrderController#async] Context initialized
2024-05-27 16:19:49 INFO [Thread-3] c.g.linyuzai.download.core.logger.DownloadLogger: Download >> [OrderController#async] Source created: [FileSource(D:\test\1.png), FileSource(D:\test\2.png), FileSource(D:\test\3.png)]
2024-05-27 16:19:49 INFO [Thread-3] c.g.linyuzai.download.core.logger.DownloadLogger: Download >> [OrderController#async] Source loaded
2024-05-27 16:19:49 INFO [Thread-3] c.g.linyuzai.download.core.logger.DownloadLogger: Download >> [OrderController#async] Source compress with file 'D:\compress_cache\a\1.zip'
2024-05-27 16:19:49 ERROR [Thread-3] c.g.linyuzai.download.core.logger.DownloadLogger: Download >> [OrderController#async] 
java.io.FileNotFoundException: \compress_cache\a\1.zip (系统找不到指定的路径。)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:289)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:230)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:179)
	at com.github.linyuzai.download.core.compress.AbstractSourceCompressor.compress(AbstractSourceCompressor.java:70)
	at com.github.linyuzai.download.core.handler.impl.CompressSourceHandler.handle(CompressSourceHandler.java:64)
	at com.github.linyuzai.download.autoconfigure.web.servlet.ServletDownloadHandlerChain.next(ServletDownloadHandlerChain.java:37)
	at com.github.linyuzai.download.core.handler.impl.LoadSourceHandler.handle(LoadSourceHandler.java:50)
	at com.github.linyuzai.download.autoconfigure.web.servlet.ServletDownloadHandlerChain.next(ServletDownloadHandlerChain.java:37)
	at com.github.linyuzai.download.core.handler.impl.CreateSourceHandler.handle(CreateSourceHandler.java:48)
	at com.github.linyuzai.download.autoconfigure.web.servlet.ServletDownloadHandlerChain.next(ServletDownloadHandlerChain.java:37)
	at com.github.linyuzai.download.autoconfigure.web.servlet.ServletDownloadConcept.lambda$doDownload$0(ServletDownloadConcept.java:36)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2024-05-27 16:19:49 INFO [Thread-3] c.g.linyuzai.download.core.logger.DownloadLogger: Download >> [OrderController#async] Source cache deleted
2024-05-27 16:19:49 INFO [Thread-3] c.g.linyuzai.download.core.logger.DownloadLogger: Download >> [OrderController#async] Source resource released
2024-05-27 16:19:49 INFO [Thread-3] c.g.linyuzai.download.core.logger.DownloadLogger: Download >> [OrderController#async] Context destroyed
2024-05-27 16:19:49 INFO [Thread-3] c.g.linyuzai.download.core.logger.DownloadLogger: Download >> [OrderController#async] Time spent 0.0512109 s

**Comment by guixin29** [comment]
![图片](https://github.com/Linyuzai/concept/assets/28587546/87db02a0-9991-4757-8e1a-7a80c5e99384)

**Comment by guixin29** [comment]
![图片](https://github.com/Linyuzai/concept/assets/28587546/e7628700-503d-49e9-bc07-281e7026b867)
把压缩缓存取消掉，暂时可以了。。。

**Comment by Linyuzai** [comment]
好像是因为设置的名称相当于多了一层目录，之前没有想到会取这样的名称，目前的方案是可以监听SourceFileCompressionEvent这个事件，然后拿到对应的File对象判断一下父文件目录是不是存在，不存在的创建一下目录，应该可以解决

压缩缓存关掉也可以，关掉的话就是直接在内存处理了

**Comment by guixin29** [comment]
好的，暂时先关缓存吧，感谢。。。

**Comment by guixin29** [comment]
下载网络文件的时候名称还是有问题，这个需要监听哪个事件处理。。。
Creating a new SqlSession
SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@43e62037] was not registered for synchronization because synchronization is not active
==>  Preparing: SELECT * FROM `cms_order` WHERE `id` = ? AND `deleted` = 0 AND `tenantId` = ?
==> Parameters: 35521928340000155(String), 31540140099000185(String)
<==    Columns: id, tenantId, model, name, avatar, mobile, baby, code, sliderDate, sliderTime, sliderBy, seriesId, storeId, shoots, status, descr, version, json, createBy, createTime, updateBy, updateTime, deleted
<==        Row: 35521928340000155, 31540140099000185, 2, ..., null, 17323166070, <<BLOB>>, 202405170004, 2024-05-31, 10:00~12:00, 104709461915754496, 2, 1, <<BLOB>>, 2, null, 23, <<BLOB>>, 103240626062761984, 2024-05-17 16:13:08, 103240626062761984, 2024-05-24 12:29:21, 0
<==      Total: 1
Flex exec sql took 2 ms >>>  SELECT * FROM `cms_order` WHERE `id` = '35521928340000155'  AND `deleted` = 0 AND `tenantId` = '31540140099000185' 
Closing non transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@43e62037]
Creating a new SqlSession
SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@10d3483e] was not registered for synchronization because synchronization is not active
==>  Preparing: SELECT `id`, `tenantId`, `orderId`, `attireId`, `file`, `url`, `thurl`, `xturl`, `n8`, `exif`, `status`, `version`, `json`, `createBy`, `createTime`, `updateBy`, `updateTime`, `deleted` FROM `cms_image` WHERE `tenantId` = ? AND (`orderId` = ? AND `url` IS NOT NULL ) AND `deleted` = ?
==> Parameters: 31540140099000185(String), 35521928340000155(String), 0(Integer)
<==    Columns: id, tenantId, orderId, attireId, file, url, thurl, xturl, n8, exif, status, version, json, createBy, createTime, updateBy, updateTime, deleted
<==        Row: 1, 31540140099000185, 35521928340000155, 30226492982000168, http://s3.eapye.com/j2es/2024/05/17/35521928340000155/35522295051000166.jpeg, http://s3.eapye.com/j2es/2024/05/17/35521928340000155/35522295715000190.jpeg, http://s3.eapye.com/j2es/2024/05/17/35521928340000155/35522295715000190.jpeg.min.jpg, http://s3.eapye.com/j2es/2024/05/17/35521928340000155/35522295715000190.jpeg, null, null, 0, 0, <<BLOB>>, null, 2024-05-17 16:19:19, null, 2024-05-17 16:19:19, 0
<==        Row: 2, 31540140099000185, 35521928340000155, 30226492982000168, http://s3.eapye.com/j2es/2024/05/17/35521928340000155/35522295051000166.jpeg, http://s3.eapye.com/j2es/2024/05/17/35521928340000155/35522295715000190.jpeg, http://s3.eapye.com/j2es/2024/05/17/35521928340000155/35522295715000190.jpeg.min.jpg, http://s3.eapye.com/j2es/2024/05/17/35521928340000155/35522295715000190.jpeg, null, null, 0, 0, <<BLOB>>, null, 2024-05-17 16:19:19, null, 2024-05-17 16:19:19, 0
<==        Row: 3, 31540140099000185, 35521928340000155, 30226492982000168, http://s3.eapye.com/j2es/2024/05/17/35521928340000155/35522295051000166.jpeg, http://s3.eapye.com/j2es/2024/05/17/35521928340000155/35522295715000190.jpeg, http://s3.eapye.com/j2es/2024/05/17/35521928340000155/35522295715000190.jpeg.min.jpg, http://s3.eapye.com/j2es/2024/05/17/35521928340000155/35522295715000190.jpeg, null, null, 0, 0, <<BLOB>>, null, 2024-05-17 16:19:19, null, 2024-05-17 16:19:19, 0
<==        Row: 36025368425000119, 31540140099000185, 35521928340000155, 30227730385000155, http://s3.eapye.com/j2es/2024/05/31/35521928340000155/36025560712000178.cr2, http://s3.eapye.com/j2es/2024/05/23/35521928340000155/36025560712000178.jpeg, http://s3.eapye.com/j2es/2024/05/23/35521928340000155/36025560712000178.jpeg.min.jpg, null, null, 110, 0, 6, <<BLOB>>, 103240626062761984, 2024-05-23 12:03:48, 103240626062761984, 2024-05-23 12:36:41, 0
<==        Row: 36042347915000186, 31540140099000185, 35521928340000155, 30227730385000155, http://s3.eapye.com/j2es/2024/05/31/35521928340000155/36042245802000140.cr2, http://s3.eapye.com/j2es/2024/05/31/35521928340000155/36042245802000140.jpg, http://s3.eapye.com/j2es/2024/05/31/35521928340000155/36042245802000140.jpg.min.jpg, null, null, 120, 0, 0, <<BLOB>>, 103240626062761984, 2024-05-23 16:46:47, 103240626062761984, 2024-05-23 16:46:47, 0
<==        Row: 4, 31540140099000185, 35521928340000155, 30226492982000168, http://s3.eapye.com/j2es/2024/05/17/35521928340000155/35522295051000166.jpeg, http://s3.eapye.com/j2es/2024/05/17/35521928340000155/35522295715000190.jpeg, http://s3.eapye.com/j2es/2024/05/17/35521928340000155/35522295715000190.jpeg.min.jpg, null, null, null, 0, 0, <<BLOB>>, null, 2024-05-17 16:19:19, null, 2024-05-17 16:19:19, 0
<==      Total: 6
Flex exec sql took 3 ms >>>  SELECT `id`, `tenantId`, `orderId`, `attireId`, `file`, `url`, `thurl`, `xturl`, `n8`, `exif`, `status`, `version`, `json`, `createBy`, `createTime`, `updateBy`, `updateTime`, `deleted` FROM `cms_image` WHERE `tenantId` = '31540140099000185' AND (`orderId` = '35521928340000155' AND `url` IS NOT NULL ) AND `deleted` = 0
Closing non transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@10d3483e]
Creating a new SqlSession
SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@6257fd82] was not registered for synchronization because synchronization is not active
==>  Preparing: SELECT `id`, `model`, `label`, `value`, `image`, `weight`, `descr`, `fixed`, `status`, `createBy`, `createTime`, `updateBy`, `updateTime`, `version`, `json`, `deleted` FROM `sys_dictionary` WHERE (`model` = ?) AND `deleted` = ?
==> Parameters: cms_n8(String), 0(Integer)
<==    Columns: id, model, label, value, image, weight, descr, fixed, status, createBy, createTime, updateBy, updateTime, version, json, deleted
<==        Row: 34657205969000193, cms_n8, 四宫格, 1, null, 1, null, 0, 0, 103240626062761984, 2024-05-07 16:01:05, 103240626062761984, 2024-05-28 16:25:41, 5, <<BLOB>>, 0
<==        Row: 34657218880000195, cms_n8, 九宫格, 2, null, 2, null, 0, 0, 103240626062761984, 2024-05-07 16:01:18, 103240626062761984, 2024-05-28 16:25:21, 5, <<BLOB>>, 0
<==      Total: 2
Flex exec sql took 2 ms >>>  SELECT `id`, `model`, `label`, `value`, `image`, `weight`, `descr`, `fixed`, `status`, `createBy`, `createTime`, `updateBy`, `updateTime`, `version`, `json`, `deleted` FROM `sys_dictionary` WHERE (`model` = 'cms_n8') AND `deleted` = 0
Closing non transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@6257fd82]
2024-05-28 18:39:57 INFO [http-nio-80-exec-1] c.g.linyuzai.download.core.logger.DownloadLogger: Download >> [OrderController#n8] Context initialized
2024-05-28 18:39:57 INFO [Thread-15] c.g.linyuzai.download.core.logger.DownloadLogger: Download >> [OrderController#n8] Source created: [OkHttpSource(http://s3.eapye.com/j2es/2024/05/17/35521928340000155/35522295715000190.jpeg), OkHttpSource(http://s3.eapye.com/j2es/2024/05/17/35521928340000155/35522295715000190.jpeg), OkHttpSource(http://s3.eapye.com/j2es/2024/05/17/35521928340000155/35522295715000190.jpeg), OkHttpSource(http://s3.eapye.com/j2es/2024/05/23/35521928340000155/36025560712000178.jpeg), OkHttpSource(http://s3.eapye.com/j2es/2024/05/31/35521928340000155/36042245802000140.jpg), OkHttpSource(http://s3.eapye.com/j2es/2024/05/17/35521928340000155/35522295715000190.jpeg)]
2024-05-28 18:39:57 ERROR [Thread-15] c.g.linyuzai.download.core.logger.DownloadLogger: Download >> [OrderController#n8] 
java.util.concurrent.ExecutionException: java.io.FileNotFoundException: \source_cache\欢笑儿童照\35522295715000190.jpeg (系统找不到指定的路径。)
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at com.github.linyuzai.download.core.load.CompletableFutureSourceLoader.concurrentLoad(CompletableFutureSourceLoader.java:28)
	at com.github.linyuzai.download.core.load.ConcurrentSourceLoader.load(ConcurrentSourceLoader.java:39)
	at com.github.linyuzai.download.core.handler.impl.LoadSourceHandler.handle(LoadSourceHandler.java:48)
	at com.github.linyuzai.download.autoconfigure.web.servlet.ServletDownloadHandlerChain.next(ServletDownloadHandlerChain.java:37)
	at com.github.linyuzai.download.core.handler.impl.CreateSourceHandler.handle(CreateSourceHandler.java:48)
	at com.github.linyuzai.download.autoconfigure.web.servlet.ServletDownloadHandlerChain.next(ServletDownloadHandlerChain.java:37)
	at com.github.linyuzai.download.autoconfigure.web.servlet.ServletDownloadConcept.lambda$doDownload$0(ServletDownloadConcept.java:36)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.io.FileNotFoundException: \source_cache\欢笑儿童照\35522295715000190.jpeg (系统找不到指定的路径。)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:289)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:230)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:179)
	at com.github.linyuzai.download.core.load.AbstractLoadableSource.load(AbstractLoadableSource.java:88)
	at com.github.linyuzai.download.core.load.CompletableFutureSourceLoader.lambda$concurrentLoad$0(CompletableFutureSourceLoader.java:21)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run$$$capture(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
2024-05-28 18:39:57 INFO [Thread-15] c.g.linyuzai.download.core.logger.DownloadLogger: Download >> [OrderController#n8] Source cache deleted
2024-05-28 18:39:57 INFO [Thread-15] c.g.linyuzai.download.core.logger.DownloadLogger: Download >> [OrderController#n8] Source resource released
2024-05-28 18:39:57 INFO [Thread-15] c.g.linyuzai.download.core.logger.DownloadLogger: Download >> [OrderController#n8] Context destroyed
2024-05-28 18:39:57 INFO [Thread-15] c.g.linyuzai.download.core.logger.DownloadLogger: Download >> [OrderController#n8] Time spent 0.0034236 s

**Comment by Linyuzai** [comment]
把 source cache 关掉，或者监听SourceCreatedEvent，拿到cachePath+name判断

**Comment by guixin29** [comment]
感谢。。。

**Comment by guixin29** [comment]
![图片](https://github.com/Linyuzai/concept/assets/28587546/686ca55d-91cf-4c4d-a0c5-2b16e9aac686)
下载下来文件损坏

**Comment by guixin29** [comment]
图片通过url  File没有问题。。。

**Comment by Linyuzai** [comment]
文件大小有问题吗，发一下代码我明天试一下，你可以跟下 OkHttpSource#loadRemote 里面是下载逻辑

**Comment by Linyuzai** [comment]
刚看代码发现线程池处理的时候没有捕获异常，不知道是不是异常被吞了。。。

**Comment by guixin29** [comment]
就是这种方式
@Download(forceCompress = true, charset = "UTF-8")
@GetMapping("download")
public DownloadOptions.Configurer ***@***.*** String orderId, @RequestParam String model, @RequestParam(required = false) Serializable[] extras) throws IOException {
    response.setHeader("Access-Control-Expose-Headers", "Content-Disposition");
    List<Image&gt; images = imageService.list(QueryWrapper.create().and(IMAGE.ORDER_ID.eq(orderId)).and(IMAGE.ID.in(extras, If::isNotEmpty)));
    if (CollectionUtils.isEmpty(images)) {
        throw new ServiceException("下载失败,资源不存在");
    }
    return new DownloadOptions.Configurer() {
        @Override
        public void configure(ConfigurableDownloadOptions options) {
            switch (model) {
                case "1":
                    // 文件
                    options.setFilename("文件.zip");
                    options.setSource(new ArrayList<&gt;() {
                        {
                            for (Image image : images) {
                                if (StringUtils.isNotBlank(image.getFile())) {
                                    add(new Source("", image.getFile()));
                                }
                            }
                        }
                    });
                    break;
                case "2":
                    // 原片
                    options.setFilename("原片.zip");
                    options.setSource(new ArrayList<&gt;() {
                        {
                            for (Image image : images) {
                                if (StringUtils.isNotBlank(image.getUrl())) {
                                    add(new Source("", image.getUrl()));
                                }
                            }
                        }
                    });
                    break;
                case "3":
                    // 设计
                    options.setFilename("设计.zip");
                    options.setSource(new ArrayList<&gt;() {
                        {
                            for (Image image : images) {
                                if (StringUtils.isNotBlank(image.getXturl())) {
                                    add(new Source("", image.getXturl()));
                                }
                            }
                        }
                    });
                    break;
                default:
                    break;
            }

        }
    };
}




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年5月28日(星期二) 晚上8:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Linyuzai/concept] concept-downlaod可以下载到服务器指定路径 (Issue #43)














 
刚看代码发现线程池处理的时候没有捕获异常，不知道是不是异常被吞了。。。

**Comment by Linyuzai** [comment]
你把charset这个配置去掉试试

**Comment by guixin29** [comment]
去掉charset，还是一样的。。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年5月28日(星期二) 晚上8:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Linyuzai/concept] concept-downlaod可以下载到服务器指定路径 (Issue #43)














 
你把charset这个配置去掉试试

**Comment by Linyuzai** [comment]
下载的时候，控制台输出的日志发一下，需要配置文件里面的日志都打开

**Comment by guixin29** [comment]
2024-05-29 10:50:50 INFO [http-nio-80-exec-6] c.g.linyuzai.download.core.logger.DownloadLogger: Download &gt;&gt; [OrderController#download] Context initialized
2024-05-29 10:50:50 INFO [http-nio-80-exec-6] c.g.linyuzai.download.core.logger.DownloadLogger: Download &gt;&gt; [OrderController#download] Source created: [OkHttpSource(http://s3.eapye.com/j2es/2024/05/17/35521928340000155/35522295715000190.jpeg), OkHttpSource(http://s3.eapye.com/j2es/2024/05/17/35521928340000155/35522295715000190.jpeg), OkHttpSource(http://s3.eapye.com/j2es/2024/05/17/35521928340000155/35522295715000190.jpeg), OkHttpSource(http://s3.eapye.com/j2es/2024/05/23/35521928340000155/36025560712000178.jpeg), OkHttpSource(http://s3.eapye.com/j2es/2024/05/31/35521928340000155/36042245802000140.jpg), OkHttpSource(http://s3.eapye.com/j2es/2024/05/17/35521928340000155/35522295715000190.jpeg)]
2024-05-29 10:50:50 INFO [http-nio-80-exec-6] c.g.linyuzai.download.core.logger.DownloadLogger: Download &gt;&gt; [OrderController#download] Source load using cache 'D:\source_cache\35522295715000190.jpeg'
2024-05-29 10:50:50 INFO [http-nio-80-exec-6] c.g.linyuzai.download.core.logger.DownloadLogger: Download &gt;&gt; [OrderController#download] Source load using cache 'D:\source_cache\35522295715000190.jpeg'
2024-05-29 10:50:50 INFO [http-nio-80-exec-6] c.g.linyuzai.download.core.logger.DownloadLogger: Download &gt;&gt; [OrderController#download] Source load using cache 'D:\source_cache\35522295715000190.jpeg'
2024-05-29 10:50:50 INFO [http-nio-80-exec-6] c.g.linyuzai.download.core.logger.DownloadLogger: Download &gt;&gt; [OrderController#download] Source load using cache 'D:\source_cache\36025560712000178.jpeg'
2024-05-29 10:50:50 INFO [http-nio-80-exec-6] c.g.linyuzai.download.core.logger.DownloadLogger: Download &gt;&gt; [OrderController#download] Source load using cache 'D:\source_cache\36042245802000140.jpg'
2024-05-29 10:50:50 INFO [http-nio-80-exec-6] c.g.linyuzai.download.core.logger.DownloadLogger: Download &gt;&gt; [OrderController#download] Source load using cache 'D:\source_cache\35522295715000190.jpeg'
2024-05-29 10:50:50 INFO [http-nio-80-exec-6] c.g.linyuzai.download.core.logger.DownloadLogger: Download &gt;&gt; [OrderController#download] Source loaded
2024-05-29 10:50:50 INFO [http-nio-80-exec-6] c.g.linyuzai.download.core.logger.DownloadLogger: Download &gt;&gt; [OrderController#download] Source compress using cache 'D:\compress_cache\35522295715000190.zip'
2024-05-29 10:50:50 INFO [http-nio-80-exec-6] c.g.linyuzai.download.core.logger.DownloadLogger: Download &gt;&gt; [OrderController#download] Source compressed 8.32M =&gt; 6.59M (79.25%)
2024-05-29 10:50:50 INFO [http-nio-80-exec-6] c.g.linyuzai.download.core.logger.DownloadLogger: Download &gt;&gt; [OrderController#download] Writing response 100.00%
2024-05-29 10:50:50 INFO [http-nio-80-exec-6] c.g.linyuzai.download.core.logger.DownloadLogger: Download &gt;&gt; [OrderController#download] Response written
2024-05-29 10:50:50 INFO [http-nio-80-exec-6] c.g.linyuzai.download.core.logger.DownloadLogger: Download &gt;&gt; [OrderController#download] Source resource released
2024-05-29 10:50:50 INFO [http-nio-80-exec-6] c.g.linyuzai.download.core.logger.DownloadLogger: Download &gt;&gt; [OrderController#download] Compression resource released
2024-05-29 10:50:50 INFO [http-nio-80-exec-6] c.g.linyuzai.download.core.logger.DownloadLogger: Download &gt;&gt; [OrderController#download] Context destroyed
2024-05-29 10:50:50 INFO [http-nio-80-exec-6] c.g.linyuzai.download.core.logger.DownloadLogger: Download &gt;&gt; [OrderController#download] Time spent 0.0523131 s





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年5月29日(星期三) 上午10:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Linyuzai/concept] concept-downlaod可以下载到服务器指定路径 (Issue #43)














 
下载的时候，控制台输出的日志发一下，需要配置文件里面的日志都打开

**Comment by Linyuzai** [comment]
不设置charset，你把缓存删掉再下载一次

**Comment by guixin29** [comment]
感谢。。。。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Linyuzai/concept"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月29日(星期三) 中午11:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Linyuzai/concept] concept-downlaod可以下载到服务器指定路径 (Issue #43)





 
不设置charset，你把缓存删掉再下载一次

**Comment by Linyuzai** [comment]
应该是你之前设置了charset，charset一般用于文本文件防止乱码的，图片和视频这些字节流的不需要设置
然后默认是会有缓存的（缓存配置可以看文档），第二次下载如果判断有缓存就不会重新下载和压缩

**Comment by guixin29** [comment]
明白了，谢谢。。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年5月29日(星期三) 中午11:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Linyuzai/concept] concept-downlaod可以下载到服务器指定路径 (Issue #43)














 
应该是你之前设置了charset，charset一般用于文本文件防止乱码的，图片和视频这些字节流的不需要设置
 然后默认是会有缓存的（缓存配置可以看文档），第二次下载如果判断有缓存就不会重新下载和压缩

**Comment by guixin29** [comment]
设置了下载结束后删除缓存，缓存文件还是在呢。。。

concept:
  download:
    source:
      cache:
        enabled: true #网络资源缓存是否启用
        path: D:/source_cache #网络资源缓存路径，默认为 user.home/concept/download
        delete: true #下载结束后网络资源缓存是否删除
    compress:
      format: zip #压缩格式
      cache:
        enabled: true #压缩缓存是否启用
        path: D:/compress_cache #压缩缓存路径，默认为 user.home/concept/download
        delete: true #下载结束后压缩缓存是否删除








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Linyuzai/concept"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月29日(星期三) 中午11:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Linyuzai/concept] concept-downlaod可以下载到服务器指定路径 (Issue #43)





 
应该是你之前设置了charset，charset一般用于文本文件防止乱码的，图片和视频这些字节流的不需要设置
 然后默认是会有缓存的（缓存配置可以看文档），第二次下载如果判断有缓存就不会重新下载和压缩

**Comment by Linyuzai** [comment]
日志有输出 Source cache deleted 和 Compression cache deleted 吗

**Comment by guixin29** [comment]
文件有删除，是我文件名包含了路径，文件父级没有删除。。。






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年5月29日(星期三) 中午11:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Linyuzai/concept] concept-downlaod可以下载到服务器指定路径 (Issue #43)














 
日志有输出 Source cache deleted 和 Compression cache deleted 吗

**Comment by guixin29** [comment]
压缩缓存可以设置compressCacheName，删除的时候就直接删除了，  下载缓存可以增加sourceCacheName么，这样多级目录应该能处理。。。



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Linyuzai/concept"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月29日(星期三) 中午11:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Linyuzai/concept] concept-downlaod可以下载到服务器指定路径 (Issue #43)





 
日志有输出 Source cache deleted 和 Compression cache deleted 吗

**Comment by Linyuzai** [comment]
文件删除了功能上就不影响，多了一级缓存目录没什么大问题

**Comment by guixin29** [comment]
好的，谢谢。。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年5月29日(星期三) 中午11:59
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Linyuzai/concept] concept-downlaod可以下载到服务器指定路径 (Issue #43)














 
文件删除了功能上就不影响，多了一级缓存目录没什么大问题
